version: "3.3"

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
        - database-data:/var/lib/postgresql/data/

volumes:
    database-data: